## Problem

$$f(w_1, w_2) = 0.1w_1^2 + 2w_2^2 \;\;\;\;\;\;\;(1)$$

In [1]:
import numpy as np

In [2]:
def df_w(w):
    dW = np.array([0.2 * w[0], 4 * w[1]])
    return dW

In [3]:
def Adam(W, dW, lr, V, S, beta1, beta2, t):
    epsilon = 1e-6
    V = beta1 * V + (1 - beta1) * dW
    S = beta2 * S + (1 - beta2) * (dW ** 2)

    V = V / (1 - beta1 ** t)
    S = S / (1 - beta2 ** t)

    W = W - lr * V / (np.sqrt(S) + epsilon)
    return W, V, S

In [4]:
def train_p1(optimizer, lr, epochs):
    W = np.array([-5, -2], dtype=np.float32)
    V = np.array([0, 0], dtype=np.float32)
    S = np.array([0, 0], dtype=np.float32)
    results = [W]
    for i in range(epochs):
        t = i + 1
        dW = df_w(W)
        W, V, S = optimizer(W, dW, lr, V, S, 0.9, 0.999, t)
        results.append(W)
    return results

In [5]:
train_p1(Adam, lr=0.2, epochs=30)

C:\Users\ACER\AppData\Local\Temp\ipykernel_12272\2911067338.py:7: RuntimeWarning: overflow encountered in divide
  S = S / (1 - beta2 ** t)


[array([-5., -2.], dtype=float32),
 array([-4.8      , -1.8000001], dtype=float32),
 array([-4.7531233, -1.753403 ], dtype=float32),
 array([-4.7444243, -1.7447685], dtype=float32),
 array([-4.742976 , -1.7433319], dtype=float32),
 array([-4.7427506, -1.7431083], dtype=float32),
 array([-4.7427173, -1.743075 ], dtype=float32),
 array([-4.7427125, -1.7430702], dtype=float32),
 array([-4.742712 , -1.7430695], dtype=float32),
 array([-4.742712 , -1.7430694], dtype=float32),
 array([-4.742712 , -1.7430694], dtype=float32),
 array([-4.742712 , -1.7430694], dtype=float32),
 array([-4.742712 , -1.7430694], dtype=float32),
 array([-4.742712 , -1.7430694], dtype=float32),
 array([-4.742712 , -1.7430694], dtype=float32),
 array([-4.742712 , -1.7430694], dtype=float32),
 array([-4.742712 , -1.7430694], dtype=float32),
 array([-4.742712 , -1.7430694], dtype=float32),
 array([-4.742712 , -1.7430694], dtype=float32),
 array([-4.742712 , -1.7430694], dtype=float32),
 array([-4.742712 , -1.7430694], d