## Problem

$$f(w_1, w_2) = 0.1w_1^2 + 2w_2^2 \;\;\;\;\;\;\;(1)$$

In [4]:
import numpy as np

In [5]:
def df_w(w):
    dW = np.array([0.2 * w[0], 4 * w[1]])
    return dW

In [6]:
def sgd_momentum(W, dW, lr, V, beta):
    V = beta * V + (1 - beta) * dW
    W = W - lr * V
    return W, V

In [7]:
def train_p1(optimizer, lr, epochs):
    W = np.array([-5, -2], dtype=np.float32)
    V = np.array([0, 0], dtype=np.float32)
    results = [W]
    for i in range(epochs):
        dW = df_w(W)
        W, V = optimizer(W, dW, lr, V, beta=0.9)
        results.append(W)
    return results

In [8]:
train_p1(sgd_momentum, lr=0.6, epochs=30)

[array([-5., -2.], dtype=float32),
 array([-4.94, -1.52], dtype=float32),
 array([-4.82672   , -0.72319996], dtype=float32),
 array([-4.6668477 ,  0.16748804], dtype=float32),
 array([-4.46696  ,  0.9289101], dtype=float32),
 array([-4.2334576,  1.3912514], dtype=float32),
 array([-3.972504 ,  1.4734583], dtype=float32),
 array([-3.6899757,  1.1938145], dtype=float32),
 array([-3.3914206,  0.6556196], dtype=float32),
 array([-3.0820239 ,  0.01389545], dtype=float32),
 array([-2.7665825, -0.5669912], dtype=float32),
 array([-2.4494863, -0.9537113], dtype=float32),
 array([-2.134706 , -1.0728686], dtype=float32),
 array([-1.8257873, -0.9226217], dtype=float32),
 array([-1.525851 , -0.5659703], dtype=float32),
 array([-1.2375982 , -0.10915118], dtype=float32),
 array([-0.9633194,  0.3281823], dtype=float32),
 array([-0.7049087,  0.6430187], dtype=float32),
 array([-0.46388018,  0.772047  ], dtype=float32),
 array([-0.24138793,  0.7028811 ], dtype=float32),
 array([-0.03824826,  0.47194034