## Problem

$$f(w_1, w_2) = 0.1w_1^2 + 2w_2^2 \;\;\;\;\;\;\;(1)$$

In [1]:
import numpy as np

In [2]:
def df_w(w):
    dW = np.array([0.2 * w[0], 4 * w[1]])
    return dW

In [3]:
def RMSProp(W, dW, lr, S, gamma):
    epsilon = 1e-6
    S = gamma * S + (1 - gamma) * (dW ** 2)
    W = W - lr * dW / (np.sqrt(S) + epsilon)
    return W, S

In [4]:
def train_p1(optimizer, lr, epochs):
    W = np.array([-5, -2], dtype=np.float32)
    S = np.array([0, 0], dtype=np.float32)
    results = [W]
    for i in range(epochs):
        dW = df_w(W)
        W, S = optimizer(W, dW, lr, S, gamma=0.9)
        results.append(W)
    return results

In [5]:
train_p1(RMSProp, lr=0.3, epochs=30)

[array([-5., -2.], dtype=float32),
 array([-4.0513196, -1.051317 ], dtype=float32),
 array([-3.4351954 , -0.59152365], dtype=float32),
 array([-2.9589348, -0.3294396], dtype=float32),
 array([-2.5654607 , -0.17756498], dtype=float32),
 array([-2.2292035 , -0.09163268], dtype=float32),
 array([-1.9362655 , -0.04494506], dtype=float32),
 array([-1.6781749 , -0.02081427], dtype=float32),
 array([-1.4493479 , -0.00903561], dtype=float32),
 array([-1.2458801 , -0.00364592], dtype=float32),
 array([-1.0649012 , -0.00135351], dtype=float32),
 array([-9.0420055e-01, -4.5644620e-04], dtype=float32),
 array([-7.6199484e-01, -1.3756353e-04], dtype=float32),
 array([-6.3677686e-01, -3.6260288e-05], dtype=float32),
 array([-5.2721363e-01, -8.1134240e-06], dtype=float32),
 array([-4.3207696e-01, -1.4747443e-06], dtype=float32),
 array([-3.5019702e-01, -2.0278571e-07], dtype=float32),
 array([-2.8043324e-01, -1.8423307e-08], dtype=float32),
 array([-2.2165851e-01, -7.6775564e-10], dtype=float32),
 ar